### ISSUE TITLE
[Feature request] Display the challenge rating

### ISSUE THREAD

**Issue by DarKDinDoN** [theripper93/automated-evocations#1]
Hello,

Thank you for this awesome module!!
Could you display the challenge rating of each creature in the list.
Some spells spawn creatures depending on the challenge rating.

**Comment by theripper93** [comment]
it will literaly auto calculate the nuber you can spawn based on CR when you cast a spell. Are you sure you would still need the cr?

**Comment by theripper93** [comment]
also i'm not gonna put the CR in because not all systems work that way

**Comment by DarKDinDoN** [comment]
How does that work?
How do you recognize creatures for spells like "Conjure Animals"?

Also, does this work with translated systems?

**Comment by theripper93** [comment]
It does not work with translated systems, it does not "recognize" the creatures, i hand selected all of them ;). As long as you have the actors imported in your game it will automagically give you the list when you cast the spell

**Comment by theripper93** [comment]
that said you could have it translated if you use the advanced comfiguration

**Comment by theripper93** [comment]
that said this are question better asked in the discord, follow the invite link in the git readme. I'll close this issue as cr is system specific so i will not add it to the dialog
