### ISSUE TITLE
multiple issues with "Spiritual weapon"

### ISSUE THREAD

**Issue by DarKDinDoN** [theripper93/automated-evocations#10]
Hello,

1. Spiritual weapon attack bonus
The macro calculation is ok, but since the spiritual weapon actor has a proficiency bonus of +2, a +2 is added to the "slash" attack roll, resulting with a wrong formula.

2. If a linked NPC is casting the spell but the NPC token is not placed on the scene, the animation is played, but failed afterwards with the following error:
![image](https://user-images.githubusercontent.com/1687854/132075169-833c9a8b-2cbf-4d15-ba5d-715f1a738027.png)

3. If a linked NPC cast the same spell multiple times with multiple tokens placed on the canvas, the first "spiritual weapon" placed as a correct damage formula of "1d8+bonus" but other tokens have a formula of "1d8+"

![image](https://user-images.githubusercontent.com/1687854/132075312-0700a03f-01ee-4e77-a5d9-d0442b4d6448.png)

**Comment by theripper93** [comment]
1. i'll have that sorted
2. the auto spells require a token on the battlefield
3. i'm not clear on what you mean exactly

**Comment by theripper93** [comment]
do you mean you have multiple of the same linked npc on the canvas?

**Comment by DarKDinDoN** [comment]
For the third issue, you can experience it with the following scenario:

- Place a character token on the canvas
- Cast "Spiritual Weapon" once and place a token on the map
- Cast "Spiritual Weapon" a second time and place a second token on the map
- The second token won't have the correct damage bonus in the "slash" attack

**Comment by theripper93** [comment]
should be fixed

**Comment by DarKDinDoN** [comment]
Yep, thx!

**Comment by DarKDinDoN** [comment]
Well, not for the "Spiritual weapon attack bonus", but I think we can susbtract the proficiency bonus simply by addind "- @prof" to the formula?

**Comment by theripper93** [comment]
I’m pretty sure the number is correct, as you make a spell attack (there is no proficiency added by the sword actor, he is nit orificent with that attack)

**Comment by DarKDinDoN** [comment]
ofc! Sorry, created my own Spiritual Weapon actor. Forgot to remove the profiency bonus.

Sorry for the trouble :/
