### ISSUE TITLE
Issue with BetterRolls5e

### ISSUE THREAD

**Issue by DarKDinDoN** [theripper93/automated-evocations#11]
Hello,

While using Spiritual Weapon with BetterRolls, if the character upcasts the spell, the automated evocations window does not appear on the screen.
If cast with the regular/normal level, the window appears.

**Comment by theripper93** [comment]
are you using both better rolls and midi perhaps?

**Comment by DarKDinDoN** [comment]
Nope, only BetterRolls.

It happens only if you upcast the spell.
And is suspect, only for items with macro like Spiritual Weapons. Might be cause spelllevel is not defined the same way with betterRoll.

Remember using macros prior to this awesome module.
Had to use `roll.BetterRoll.params.slotLevel` to retrieve the spell slot used.

**Comment by theripper93** [comment]
i already do special handling for betterrolls but maybe there is something wrong in there i'll give it a look

**Comment by theripper93** [comment]
fixed

**Comment by DarKDinDoN** [comment]
Yep, confirmed, thx! :)
