### ISSUE TITLE
Evocation window minimized cause issues

### ISSUE THREAD

**Issue by DarKDinDoN** [theripper93/automated-evocations#12]
Hello,

If the evocation window was minimized while casting a spell.
The evocation window is correctly maximized but is black and empty
![image](https://user-images.githubusercontent.com/1687854/132075468-a90f47b0-2f3e-4103-bf24-e76009aea164.png)

**Comment by theripper93** [comment]
could you elaborate, also did you test with other modules disabled first?

**Comment by DarKDinDoN** [comment]
Yes, tested with all modules disabled.

Tested on FVTT 0.8.9 & D&D 1.4.2


First open a character sheet then cast a spell with evocations.
Instead of placing an evocation on the scene, minimize the evocation window.
Then cast the same spell again.

The previously minimized evocation windows will be maximized but empty and black.

**Comment by theripper93** [comment]
i mean, why are you opening multiple... are you just intentionally trying to break it lol

**Comment by DarKDinDoN** [comment]
Kinda!
Like testing the limit of modules to know where it breaks and why.
Like to be prepared when players do smt you don't expect.

But I agree, it's an edge case :)

**Comment by theripper93** [comment]
anyways this is a foundry bug, i'm gonna add a fix and it will close also the main companion window in the process

**Comment by theripper93** [comment]
never mind, the workaround doesen't even work

**Comment by DarKDinDoN** [comment]
No worries, ultra minor issue.
