### ISSUE TITLE
Minimize character sheet

### ISSUE THREAD

**Issue by DarKDinDoN** [theripper93/automated-evocations#13]
Hello,

Would it be possible to minimize the character sheet on spell cast to we the user has a better view on the canvas?
And maximize it once the token is placed (or dismissed with right click)

**Comment by theripper93** [comment]
that's not currently plan , i'll keep the suggestion in mind

**Comment by DarKDinDoN** [comment]
Just for the record, I think Warp Gate provides that feature with the `controllingActor` option.
