### ISSUE TITLE
Crosshairs not appearing

### ISSUE THREAD

**Issue by HarryWraith** [theripper93/automated-evocations#15]
Steps to reproduce
1. Dragon a monster to the actors tab (inside customer folder).
2. Open Companions and drag and drag and drop the actor to the folder (this works)
3. Click on the companion to summon image

The companion minimizes but no actor appears. There is no magic effect. 

Notes: 
I am doing this from a player sheet as the GM.
I have tried changing permissions to owner as default

**Comment by theripper93** [comment]
this seems to be an issue with Warpgate and The Forge, update both AE and Warpgate and see if the issue is fixed

**Comment by theripper93** [comment]
be sure to be on the  1.7.2  version of warpgate

**Comment by HarryWraith** [comment]
Thanks. That worked. Just as an FYI I'd only just installed AE, and during that process it asked me to also install WG. Naturally I clicked yes. Guess it must be linked to 1.7.1.
