### ISSUE TITLE
Dragging the companions in doesn't work for me

### ISSUE THREAD

**Issue by Gedfort** [theripper93/automated-evocations#17]
I've installed the module and all of it's dependencies, everything seems to be in order, yet nothing happens when I drag the companions on the canvas from the companion manager, and I've just updated to the latest version... Anyone had this issue as well?

**Comment by theripper93** [comment]
you don't drag, you click the image and then you click on the canvas

**Comment by Gedfort** [comment]
Ah, silly me, thanks for the quick reply!
