### ISSUE TITLE
Feature Request: Toggle Option to group place/individually place multiple summons?

### ISSUE THREAD

**Issue by RogueEntityX** [theripper93/automated-evocations#18]
One thing I have missed using AE + Warp Gate as opposed to just WG, is the ability to individually place multiple summons. For example, using just a WG macro to place 4 Dancing Lights globes, I could individually place each one with this macro:
```
const summonType = "Dancing Lights";

await warpgate.spawn(summonType)
await warpgate.spawn(summonType)
await warpgate.spawn(summonType)
await warpgate.spawn(summonType)
```
resulting in this: 

https://user-images.githubusercontent.com/72455534/134093809-9e44e985-52ea-486b-a411-bfe0ad4c4bcb.mp4

However, using AE, it seems there is only the option to place them all at once in a group, similar to the ice mephits in Zephyr's Youtube tutorial (https://www.youtube.com/watch?v=VcAz8t6-lTY) around the 21:20 mark.

I'd like it if there were the choice to place them individually, as there is with just Warp Gate, if this is possible. Whether a global settings toggle for it (all or nothing), or perhaps an individual checkbox when a creature is selected in the companions window.

Thanks for the consideration.

**Comment by theripper93** [comment]
Automated evocations is really ment to be a simple interface, i'm not going to add that. If you want tho, you can add any code you wish in the AE companion macros, so when you spawn 1 dancing light code can be called to spawn 3 more through a regular WG macro
