### ISSUE TITLE
Not an issue but an idea

### ISSUE THREAD

**Issue by paulcheeba** [theripper93/automated-evocations#20]
Automated Wildshapes! I had a thought last night that with a bit of modification you could copy your module and change it so a player can wildshape from it. Essentially a place for the players to store their wild shapes. I feel like there would be too many tokens if used for polymorph but that could be up to the player.

**Comment by theripper93** [comment]
That is so niche that it’s not worth the effort. You could simply crate a folder in the sidebar with the creatures

**Comment by paulcheeba** [comment]
Yeah, hey, fair enough.
