### ISSUE TITLE
Summoned companions coming in with elevation zero instead of summoner level by default (Levels module)

### ISSUE THREAD

**Issue by TogaParty** [theripper93/automated-evocations#24]
Summoned companions coming in with elevation zero instead of summoner level by default (Levels module)

It would be good if the default elevation of the summoned companion matched the summoning actor.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.
