### ISSUE TITLE
Summoning with Gm Permission

### ISSUE THREAD

**Issue by emomgo3** [theripper93/automated-evocations#29]
Hello, i wanted to ask if it is plausible to implement a feature which enables players to summon companions with GM permission instead of giving players all Permissions needed for summoning?
As far as i know [https://github.com/MrVauxs/pf2e-jb2a-macros](url) "Summon Anything" macro also uses the Warpgate API but doesnt require the players to possess extra permissions by simply asking for gm approval, however the macros provided are not useful for things like summoning spiritual weapon tokens or other player-non-summoning-spell related summons. For this your module is alot easier to use.

![image](https://user-images.githubusercontent.com/48028314/204611741-49ad4990-db73-455c-8f78-81eed27b5bfc.png)

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.

**Comment by emomgo3** [comment]
Oh my, you are right! im sorry, will take that to the discord.
