### ISSUE TITLE
More Animations

### ISSUE THREAD

**Issue by brunocalado** [theripper93/automated-evocations#3]
Hi! This is a great module!!!

Is it possible to let the user add animations?
![image](https://user-images.githubusercontent.com/4999783/130790633-c9894951-9341-4f5f-b1d8-a1fcfefeb3b3.png)

The easiest way would be let the user set a macro compendium in the settings and the **automated-evocations** would read the sequencer animation from it directly.
  ```
let pack = game.packs.get(compendiumName);
let macro = ( await pack.getDocuments() ).find(i => (i.data.name==macroName) );
```

**Comment by theripper93** [comment]
i was just adding the custom animations, it's live in the current version, check the documentation for the how to

**Comment by brunocalado** [comment]
Thank you. I'm trying to reproduce without success. Can you help me?

Where should I add this?
```
const customanims = {
  energy2: {
    fn: "light2",
    time: 650,
    name: "Energy 2",
  },
};
game.settings.set(AECONSTS.MN, "customanimations", customanims);
```

Thank you.
