### ISSUE TITLE
randomOffset - This method has been deprecated

### ISSUE THREAD

**Issue by brunocalado** [theripper93/automated-evocations#30]
Hi.

There is one deprecated method on crescendo effect. I don't know if it will be removed in new sequencer releases. 

`Sequencer | Effect | randomOffset - This method has been deprecated, please use randomOffset as a second parameter on atLocation, stretchTo, etc.`

![image](https://user-images.githubusercontent.com/4999783/215086746-b6980624-fc28-4524-9c48-62003206b1f5.png)

**Comment by theripper93** [comment]
fixed
