### ISSUE TITLE
Folders for Companion Actors?

### ISSUE THREAD

**Issue by Raezenkane** [theripper93/automated-evocations#31]
First of all, GREAT JOB on this Module, it is exacly what I was looking for!
What I am trying to do is to automate Moster Summoning spells, and this works fine!
As an aside, if you know something that works better just for Monster Summoning, please let me know.
This is actually **Not An Issue**, but I didn't see "Feature Request"
Is it possible for you to add Folders to the Companions Dialog?
My idea is to be able to create a "Summon Monster 1" Folder and drag Dire Rat, Dog, Dolphin, etc. into it.
Then make a "Summon Monster 2 Folder and similarly drag that spell's monsters in.
I am in the Foundry Discord for PF1e, Raezenkane#4735, if you have any questions.
Thanks for the Module, and thanks for listening!

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
