### ISSUE TITLE
Ability to define an animation type in a custom spell

### ISSUE THREAD

**Issue by DarKDinDoN** [theripper93/automated-evocations#9]
Hey,

Would be cool if we can configure a custom spell with an animation. By default, all are set to "Air".

**Comment by theripper93** [comment]
well, you can already :P, when you define your customs like this
      {
        creature: "Demon name 1",
        number: 1,
      },

you can add an animation field

      {
        creature: "Demon name 1",
        number: 1,
        animation: "fire",
      },

**Comment by DarKDinDoN** [comment]
Cool!

**Comment by theripper93** [comment]
added it to the documentation
